// vue/src/pages/Demo.vue
<template>
  <div class="content">
    <div class="md-layout">
      <div class="md-layout-item md-medium-size-100 md-xsmall-size-100 md-size-100">
        <md-card>
          <md-card-header data-background-color="green">
            <h4 class="title">People</h4>
            <hr>
            <p>This page demonstrates audit functionality.</p>
            <p style="margin-bottom:0">
              Using pgAdmin you can track changes made by the app. We are
              dealing with
              <b>Persons</b> table.
            </p>
            <br>
            <p style="margin-bottom:0">
              Create record and have a look at
              <b>CreationTime</b>,
              <b>CreatorID</b> and
              <b>TenantID</b>.
            </p>
            <p style="margin-bottom:0">
              Modify record and have a look at
              <b>ModificationTime</b> and
              <b>ModifierID</b>.
            </p>
            <p style="margin-bottom:0">
              Delete record and have a look at
              <b>DeletionTime</b> and
              <b>DeleterID</b>.
            </p>
            <br>
            <p style="margin-bottom:0">
              Try switching between tenants ('restaura' and 'galeriasenda') and see that
              the
              app only pulls records which belong to current tenant.
            </p>
            <br>
            <p style="margin-bottom:0">
              Note that we've applied Dynamic Filter to avoid pulling soft-deleted
              records.
            </p>
          </md-card-header>
          <md-card-content>
            <md-button
              class="md-icon-button md-raised"
              style="float: right;"
              @click="showPersonDialog(null)"
            >
              <md-icon>add</md-icon>
            </md-button>
            <br>
            <br>
            <div>
              <md-table v-model="persons" :table-header-color="tableHeaderColor">
                <md-table-row slot="md-table-row" slot-scope="{ item }">
                  <md-table-cell md-label="Name">{{ item.name }}</md-table-cell>
                  <md-table-cell md-label="Description">{{ item.description }}</md-table-cell>
                  <md-table-cell md-label>
                    <md-button
                      class="md-dense md-raised md-primary"
                      @click="showPersonDialog(item)"
                    >Edit</md-button>
                  </md-table-cell>
                  <md-table-cell md-label>
                    <md-button
                      class="md-dense md-raised md-primary"
                      @click="deletePerson(item)"
                    >Delete</md-button>
                  </md-table-cell>
                </md-table-row>
              </md-table>
            </div>
          </md-card-content>
        </md-card>
      </div>
    </div>

    <div>
      <md-dialog :md-active.sync="showDialog">
        <md-dialog-title v-if="!id">Add Person</md-dialog-title>
        <md-dialog-title v-if="id">Update Person</md-dialog-title>

        <md-field>
          <label>Name</label>
          <md-input v-model="name"></md-input>
        </md-field>

        <md-field>
          <label>Description</label>
          <md-textarea v-model="description"></md-textarea>
        </md-field>

        <md-dialog-actions>
          <md-button class="md-secondary" @click="showDialog = false">Cancel</md-button>
          <md-button class="md-primary" v-if="!id" @click="add()">Add</md-button>
          <md-button class="md-primary" v-if="id" @click="update()">Update</md-button>
        </md-dialog-actions>
      </md-dialog>
    </div>
  </div>
</template>

<script>
import { SimpleTable, OrderedTable } from "@/components";
import http from "../axios-helper/http";

export default {
  components: {
    OrderedTable,
    SimpleTable
  },
  props: {
    tableHeaderColor: {
      type: String,
      default: ""
    }
  },
  data() {
    return {
      selected: [],
      persons: [],
      showDialog: false,
      name: "",
      description: "",
      id: null
    };
  },
  methods: {
    reset() {
      this.name = "";
      this.description = "";
      this.id = null;
    },
    showPersonDialog(person) {
      this.reset();

      if (person !== null) {
        this.id = person.id;
        this.name = person.name;
        this.description = person.description;
      }

      this.showDialog = true;
    },
    add() {
      var self = this;
      http
        .post("http://localhost:8080/api/Person/Add", {
          name: self.name,
          description: self.description
        })
        .then(function(response) {
          self.loadData();
          self.showDialog = false;
        });
    },
    update() {
      var self = this;
      http
        .post("http://localhost:8080/api/Person/Update", {
          id: self.id,
          name: self.name,
          description: self.description
        })
        .then(function(response) {
          self.loadData();
          self.showDialog = false;
        });
    },
    deletePerson(person) {
      var self = this;
      http
        .post("http://localhost:8080/api/Person/Delete", {
          id: person.id
        })
        .then(function(response) {
          self.loadData();
          self.showDialog = false;
        });
    },
    loadData() {
      var self = this;
      http
        .get("http://localhost:8080/api/Person/GetAll")
        .then(function(response) {
          self.persons = response.data;
        });
    }
  },
  created: function() {
    this.loadData();
  }
};
</script>

// angular/src/app/layout/demo/demo.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { routerTransition } from '../../router.animations';
import { DomSanitizer } from '@angular/platform-browser';
import { ComponentBase } from '@shared/component-base';
import { NgbModal, ModalDismissReasons, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { PersonServiceProxy, PersonDto } from '@shared/service-proxies/service-proxies';
import { ToastrService } from 'ngx-toastr';

@Component({
  templateUrl: './demo.component.html',
  styleUrls: ['./demo.component.scss'],
  animations: [routerTransition()]
})
export class DemoComponent extends ComponentBase implements OnInit {

  closeResult: string;

  private input: PersonDto;

  private persons: PersonDto[];

  private modalReference: NgbModalRef;

  constructor(
    private personService: PersonServiceProxy,
    injector: Injector,
    sanitizer: DomSanitizer,
    private modalService: NgbModal,
    private toastr: ToastrService
  ) {
    super(injector);
  }

  ngOnInit() {
    this.loadPersons();
  }

  loadPersons(): void {
    this.personService.getAll()
      .finally(() => { })
      .subscribe((result: PersonDto[]) => {
        this.persons = result;
      });
  }

  open(content) {

    this.input = new PersonDto();

    this.modalReference = this.modalService.open(content);

    this.modalReference.result.then((result) => {
      this.closeResult = `Closed with: ${result}`;
    }, (reason) => {
      this.closeResult = `Dismissed ${this.getDismissReason(reason)}`;
    });
  }

  edit(person: PersonDto, content: any) {
    this.input = person;
    this.modalReference = this.modalService.open(content);

    this.modalReference.result.then((result) => {
      this.closeResult = `Closed with: ${result}`;
    }, (reason) => {
      this.closeResult = `Dismissed ${this.getDismissReason(reason)}`;
    });
  }

  delete(person: PersonDto) {

    this.personService.delete(person)
      .finally(() => { })
      .subscribe(() => {
        this.toastr.info(`Person '${person.name}' has been deleted.`, 'Person Deleted');
        this.loadPersons();
      });
  }

  save() {

    if (this.input.id > 0) {

      this.personService.update(this.input)
        .finally(() => { })
        .subscribe(() => {
          this.toastr.success(`Person '${this.input.name}' has been updated.`, 'Person Updated');
          this.modalReference.close();
          this.loadPersons();
        });

    } else {

      this.personService.add(this.input)
        .finally(() => { })
        .subscribe(() => {
          this.toastr.success(`Person '${this.input.name}' has been created.`, 'Person Created');
          this.modalReference.close();
          this.loadPersons();
        });

    }

  }

  private getDismissReason(reason: any): string {
    if (reason === ModalDismissReasons.ESC) {
      return 'by pressing ESC';
    } else if (reason === ModalDismissReasons.BACKDROP_CLICK) {
      return 'by clicking on a backdrop';
    } else {
      return `with: ${reason}`;
    }
  }
}

<div [@routerTransition]>
    <app-page-header [heading]="'Demo'" [icon]="'fa-pie-chart'"></app-page-header>

    <div class="row">

        <div class="col-lg-12">
            <div class="alert alert-info" style="font-size:12px">
                <p>This page demonstrates audit functionality.</p>
                <p style="margin-bottom:0">Using pgAdmin you can track changes made by the app. We are
                    dealing with <b>Persons</b> table.</p>
                <br>
                <p style="margin-bottom:0">Create record and have a look at <b>CreationTime</b>, <b>CreatorID</b> and
                    <b>TenantID</b>.</p>
                <p style="margin-bottom:0">Modify record and have a look at <b>ModificationTime</b> and <b>ModifierID</b>.</p>
                <p style="margin-bottom:0">Delete record and have a look at <b>DeletionTime</b> and <b>DeleterID</b>.</p>
                <br>
                <p style="margin-bottom:0">Try switching between tenants ('restaura' and 'galeriasenda') and see that
                    the
                    app only pulls records which belong to current tenant.</p>
                <br>
                <p style="margin-bottom:0">Note that we've applied Dynamic Filter to avoid pulling soft-deleted
                    records.</p>
            </div>
        </div>

        <div class="col-lg-12 col-md-12">

            <div class="card mb-3">
                <div class="card-header">
                    People
                    <button class="btn-xs pull-right" (click)="open(content)">
                        <i class="fa fa-plus-square"></i>
                    </button>
                    <ng-template #content let-c="close" let-d="dismiss">
                        <div class="modal-header">
                            <h4 class="modal-title">{{input.id > 0 ? 'Update Person' : 'Add Person'}}</h4>
                            <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            <fieldset class="form-group">
                                <input class="form-control" [(ngModel)]="input.name" placeholder="Name..." required>
                            </fieldset>

                            <fieldset class="form-group">
                                <textarea class="form-control" [(ngModel)]="input.description" rows="3" placeholder="Description..."
                                    required></textarea>
                            </fieldset>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" (click)="save()">{{input.id > 0 ? 'Update' :
                                'Add'}}</button>
                            <button type="button" class="btn btn-secondary" (click)="c('Close click')">Close</button>
                        </div>
                    </ng-template>
                </div>
                <div class="card-body table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr *ngFor="let person of persons">
                                <th scope="row">{{person.id}}</th>
                                <td>{{person.name}}</td>
                                <td>{{person.description}}</td>
                                <td>
                                    <button class="btn btn-secondary" (click)="edit(person, content)">Edit</button>
                                </td>
                                <td>
                                    <button style="margin-left: 10px" class="btn btn-secondary" (click)="delete(person)">Delete</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
